### ISSUE TITLE
make a dev branch

### ISSUE THREAD

**Issue by Josephrp** [Tonic-AI/DataTonic#9]
**We need a dev branch, or branches for each open issue.**

currently : 
- trulens evaluation
- interface 
- app + coding tasks

**Comment by Josephrp** [comment]
we'll need to add a contributing guide to the readme @jsaluja ;-)

**Comment by twilwa** [comment]
https://github.com/Tonic-AI/DataTonic/tree/dev

general dev branch to protect main -- please modify your upstreams to push to dev branch rather than main. once dev branch is stable, we can create pr's from dev to main as a team if we're happy with it. let me know if you need help with this.

after forking the repo, i've currently created yikes-dev on my copy, but if we'd like to standardize branch names per-issue, i'll start using the naming convention after my first contribution to dev and the closure of my current branch.

i think it's best to leave this issue open until we all confirm our repos are configured correctly in the agreed-upon configuration, so please leave a comment on the issue once you've got your setup finished, and whoever the last commenter is can go ahead and close the ticket.
